### ISSUE TITLE
Nifi chart has no stable UUID in flow.xml in the ConfigMap

### ISSUE THREAD

**Issue by lucasfcnunes** [cetic/helm-charts#6]
I expected a stable apply/sync of the chart. The down side is that it creates lots of unnecessary revisions.

Diff (helmfile diff):
![image](https://github.com/cetic/helm-charts/assets/29926675/8e5a69bc-eec6-4fcd-9fe8-316bf0fe67d7)
Template (it's caused by `{{ default uuidv4 }}` not having a stable result):
![image](https://github.com/cetic/helm-charts/assets/29926675/0c28b2c8-cf3b-4319-b505-2175345164e2)

Thanks!

**Comment by banzo** [comment]
Thank you, could you create a bug report in the appropriate repo: https://github.com/cetic/helm-nifi/issues instead?
